<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-K348FQ4G" failures="2" tests="9" name="Test" time="53.436" errors="0" timestamp="2024-03-20T20:52:29 IST">
  <testcase classname="test.LoginTest" name="verifyLogin" time="1.227"/>
  <testcase classname="test.ClientsTest" name="verifyCreateClient" time="4.008"/>
  <testcase classname="test.ClientsTest" name="verifyClientSearch" time="1.488">
    <failure type="java.lang.AssertionError" message="expected [AEK] but found [AE4]">
      <![CDATA[java.lang.AssertionError: expected [AEK] but found [AE4]
at test.ClientsTest.verifyClientSearch(ClientsTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyClientSearch -->
  <testcase classname="test.ClientsTest" name="verifyEditClient" time="3.1"/>
  <testcase classname="test.ClientsTest" name="verifyDeleteCompanyName" time="6.634">
    <failure type="java.lang.AssertionError" message="expected [No record found.] but found [1116]">
      <![CDATA[java.lang.AssertionError: expected [No record found.] but found [1116]
at test.ClientsTest.verifyDeleteCompanyName(ClientsTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyDeleteCompanyName -->
  <testcase classname="test.ItemsTest" name="verifyCreateItems" time="3.566"/>
  <testcase classname="test.ItemsTest" name="verifySearchItem" time="2.047"/>
  <testcase classname="test.ItemsTest" name="verifyEditItem" time="3.56"/>
  <testcase classname="test.ItemsTest" name="verifyDeleteItem" time="2.991"/>
</testsuite> <!-- Test -->
